steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rfc-flows-image', '.' ]
images:
- 'gcr.io/$PROJECT_ID/rfc-flows-image'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', 'gcr.io/$PROJECT_ID/rfc-flows-image', '.' ]
